config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#homepage"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "admin/login", to: "sessions#create_admin"
  delete "logout", to: "sessions#destroy"
  delete "admin/logout", to: "sessions#destroy_admin"

  resources :users
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "books#index"
    get "login", to: "admin#new"
    get "search", to: "admin#index"
    resources :books
    resources :authors
    resources :publishers
    resources :categories
    resources :requests
    resources :users
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :subcategory
  belongs_to :author
  belongs_to :publisher
  has_one :category, through: :subcategory

  has_many :comments, dependent: :destroy
  has_many :follow_books, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :image, PictureUploader

  validates :title, presence: true, length: {maximum: Settings.max_name_email}
  validates :image, presence: true
  validates :description, presence: true
  validates :current, presence: true
  validates :page_number, presence: true
  validates :author_id, presence: true
  validates :subcategory_id, presence: true
  validates :publisher_id, presence: true

  delegate :name, to: :subcategory, prefix: true, allow_nil: true
  delegate :name, to: :author, prefix: true
  delegate :name, to: :publisher, prefix: true
  delegate :name, to: :category, prefix: true

  def send_notification_email(users, book)
    users.each do |user|
      UserMailer.book_notification(user, book).deliver
    end
  end

  scope :list_book_newest, -> {order created_at: :desc}
  scope :list_book_newest_limit, -> limit {order(created_at: :desc).limit(limit)}
  scope :list_book_high_rating, -> limit do
    joins(:rates).select("books.*, avg(rates.rates) as avg_rating,
      count(rates.id) as number_of_rates")
     .group("books.id").order("avg_rating DESC, number_of_rates DESC").limit(limit)
  end
  scope :list_book_by_author, -> id do
    joins(:author).select("books.*").where "authors.id = ?", "#{id}"
  end
  scope :search_book_by_title, -> search {where "title like ?", "%#{search}%"}
  scope :search_book_by_author, -> search do
    joins(:author).where "authors.name like ?", "%#{search}%"
  end
  scope :search_book_by_category, -> search do
    joins(:category).select("books.*").where "categories.name like ?", "%#{search}%"
  end
  scope :search_book_by_subcategory, -> search do
    joins(:subcategory).where "subcategories.name like ?", "%#{search}%"
  end
  scope :search_book_by_publisher, -> search do
    joins(:publisher).where "publishers.name like ?", "%#{search}%"
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :verify_admin
  before_action :load_book, only: [:edit, :destroy, :update]
  before_action :load_author, exept: [:show, :destroy]
  before_action :load_category, exept: [:show, :destroy]
  before_action :load_publisher, exept: [:show, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:create, :update]

  layout "admin"

  def new
    @book = Book.new
  end

  def index
    case
    when params[:key]
      case
      when params[:find_by] == Book.name
        @books = Book.search_book_by_title(params[:key]).list_book_newest.
          paginate page: params[:page], per_page: Settings.per_page
      when params[:find_by] == Author.name
        @books = Book.search_book_by_author(params[:key]).list_book_newest.
          paginate page: params[:page], per_page: Settings.per_page
      when params[:find_by] == Subcategory.name
        @books = Book.search_book_by_subcategory(params[:key]).
          list_book_newest.paginate page: params[:page], per_page: Settings.per_page
      else
        @books = Book.search_book_by_publisher(params[:key]).
          list_book_newest.paginate page: params[:page], per_page: Settings.per_page
      end
    else
      @books = Book.list_book_newest.paginate page: params[:page],
        per_page: Settings.per_page
    end
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def create
    @book = Book.new book_params
    if @book.save
      @users_follow = User.list_users_follow_author @book.author_id
      @book.send_notification_email(@users_follow, @book) if @users_follow.present?
      flash[:success] = t "books.add_book_success"
      redirect_to admin_books_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "books.update_success"
      redirect_to admin_books_url
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "books.delete_success"
    else
      flash[:danger] = t "books.delete_fail"
    end
    redirect_to admin_books_url
  end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:warning] = t "books.book_not_found"
    redirect_to admin_books_url
  end

  def load_category
    @categories = Subcategory.list_subcategory_order_name
  end

  def load_author
    @authors = Author.list_author_order_name
  end

  def load_publisher
    @publishers = Publisher.list_publisher_order_name
  end

  def book_params
    params.require(:book).permit :title, :image, :description, :author_id,
      :subcategory_id, :publisher_id, :current, :page_number
  end
end

app/views/admin/books/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("books.edit_book") %></h3>
    </div>
    <div class="modal-body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= form_for [:admin, @book], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @book.errors[:image].any? %>
            <p><%= @book.errors[:image].first %></p>
          <% end %>
          <div class="img-avatar bg">
            <% if @book.image.present? %>
              <%= image_tag @book.image, alt: t("books.image_alt"), id: "thumb" %>
            <% else %>
              <img id="thumb" />
            <% end %>
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control",
                readonly: true, placeholder: t("books.choose_book_image") %>
              <%= f.file_field :image, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @book.errors[:title].any? %>
            <p><%= @book.errors[:title].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :title, class: "form-control",
              placeholder: t("required") %>
            <%= f.label :title, t("books.title"), for: "book_title" %>
          </div>
          <div class="errors-group">
            <% if @book.errors[:page_number].any? %>
              <p><span><%= @book.errors[:page_number].first %></span></p>
            <% end %>
            <% if @book.errors[:current].any? %>
              <p><span><%= @book.errors[:current].first %></span></p>
            <% end %>
          </div>
          <div class="form-group input-group">
            <span class="has-float-label">
              <%= f.number_field :page_number, class: "form-control",
                min: Settings.min_page_number, placeholder: t("required") %>
              <%= f.label :page_number, t("books.page_number"),
                for: "book_page_number" %>
            </span>
            <span class="has-float-label">
              <%= f.number_field :current, class: "form-control",
                min: Settings.min_current_book, placeholder: t("required") %>
              <%= f.label :current, t("books.current"), for: "book_current" %>
            </span>
          </div>
          <% if @book.errors[:description].any? %>
            <p><%= @book.errors[:description].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.cktext_area :description, class: "form-control",
              id: "description", placeholder: t("required"),
              ckeditor: {toolbar: 'booktoolbar'} %>
            <%= f.label :description, t("books.desciption"), for: "description" %>
          </div>
          <% if @book.errors[:author_id].any? %>
            <p><%= @book.errors[:author_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select :author_id,
              options_for_select(@authors.collect{|a| [a.name, a.id]},
              @book.author_id.present? ? @book.author_id : ""), {},
              class: "form-control custom-select" %>
            <label for="book_author_id"><%= t "author" %></label>
          </div>
          <% if @book.errors[:category_id].any? %>
            <p><%= @book.errors[:category_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select :category_id,
              options_for_select(@categories.collect{|c| [c.name, c.id]},
              @book.category_id.present? ? @book.category_id : ""), {},
              class: "form-control custom-select" %>
            <label for="book_category_id"><%= t "category" %></label>
          </div>
          <% if @book.errors[:publisher_id].any? %>
            <p><%= @book.errors[:publisher_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select :publisher_id,
              options_for_select(@publishers.collect{|p| [p.name, p.id]},
              @book.publisher_id.present? ? @book.publisher_id : ""), {},
              class: "form-control custom-select" %>
            <label for="book_publisher_id"><%= t "publisher" %></label>
          </div>
        </div>
        <%= f.submit t("update"), id: "submit_book",
          class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/books/_index.html.erb
<tr>
  <td><%= col_serial book_counter %></td>
  <td><%= title_limit_book book.title %></td>
  <td><%= name_limit_book book.author_name %></td>
  <td><%= name_limit_book book.category_name %></td>
  <td><%= name_limit_book book.publisher_name %></td>
  <td><%= book.current %></td>
  <td><%= book.page_number %></td>
  <td><%= raw description_limit book.description %></td>
  <td>
    <%= image_tag book.image, alt: t("books.image_alt") %>
    <div class="edit-delete">
      <%= link_to "", edit_admin_book_path(book), remote: true,
        class: "glyphicon glyphicon-pencil"%>
      <%= link_to "", admin_book_path(book), method: :delete,
        data: {confirm: t("books.confirm_delete")},
        class: "glyphicon glyphicon-remove" %>
    </div>
  </td>
</tr>

app/views/admin/books/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("books.new_book") %></h3>
    </div>
    <div class="modal-body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= form_for [:admin, @book], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @book.errors[:image].any? %>
            <p><%= @book.errors[:image].first %></p>
          <% end %>
          <div class="img-avatar bg">
            <img id="thumb" />
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control",
                readonly: true, placeholder: t("books.choose_book_image") %>
              <%= f.file_field :image, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @book.errors[:title].any? %>
            <p><%= @book.errors[:title].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :title, class: "form-control", id: "title",
              placeholder: t("required") %>
            <%= f.label :title, t("books.title"), for: "title" %>
          </div>
          <div class="errors-group">
            <% if @book.errors[:page_number].any? %>
              <p><span><%= @book.errors[:page_number].first %></span></p>
            <% end %>
            <% if @book.errors[:current].any? %>
              <p><span><%= @book.errors[:current].first %></span></p>
            <% end %>
          </div>
          <div class="form-group input-group">
            <span class="has-float-label">
              <%= f.number_field :page_number, class: "form-control", id: "page_number",
                min: Settings.min_page_number, placeholder: t("required") %>
              <%= f.label :page_number, t("books.page_number"), for: "page_number" %>
            </span>
            <span class="has-float-label">
              <%= f.number_field :current, class: "form-control", id: "current",
                min: Settings.min_current_book, placeholder: t("required") %>
              <%= f.label :current, t("books.current"), for: "current" %>
            </span>
          </div>
          <% if @book.errors[:description].any? %>
            <p><%= @book.errors[:description].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.cktext_area :description, class: "form-control",
              id: "description", placeholder: t("required"),
              ckeditor: {toolbar: 'booktoolbar'} %>
            <%= f.label :description, t("books.desciption"), for: "description" %>
          </div>
          <% if @book.errors[:author_id].any? %>
            <p><%= @book.errors[:author_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select "author_id",
              options_for_select(@authors.collect{|a| [a.name, a.id]}), {},
              class: "form-control custom-select" %>
            <label for="book_author_id"><%= t "author" %></label>
          </div>
          <% if @book.errors[:category_id].any? %>
            <p><%= @book.errors[:category_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select "category_id",
              options_for_select(@categories.collect{|c| [c.name, c.id]}), {},
              class: "form-control custom-select" %>
            <label for="book_category_id"><%= t "category" %></label>
          </div>
          <% if @book.errors[:publisher_id].any? %>
            <p><%= @book.errors[:publisher_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select "publisher_id",
              options_for_select(@publishers.collect{|p| [p.name, p.id]}), {},
              class: "form-control custom-select" %>
            <label for="book_publisher_id"><%= t "publisher" %></label>
          </div>
        </div>
        <%= f.submit t("books.add_new"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<div class="manage">
  <div class="btn-head">
    <%= link_to t("books.new_book"), new_admin_book_path, remote: true,
      class: "btn btn-success btn-new" %>
    <%= link_to t("export"), admin_books_path(format: :xlsx),
      class: "btn btn-danger btn-export" %>
  </div>
  <div class="list">
    <div>
      <strong><%= t "books.list_book" %></strong>
      <% flash.each do |key, message| %>
        <span class="alert-<%= key %>"><%= message %></span>
      <% end %>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="stt"><%= t "stt" %></th>
          <th class="title"><%= t "books.title" %></th>
          <th class="name"><%= t "author" %></th>
          <th class="name"><%= t "category" %></th>
          <th class="name"><%= t "publisher" %></th>
          <th class="current"><%= t "books.current" %></th>
          <th class="current"><%= t "books.pages" %></th>
          <th class="description"><%= t "books.description" %></th>
          <th class="image"><%= t "image" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "index", collection: @books, as: :book %>
      </tbody>
    </table>
    <%= will_paginate @books %>
  </div>
</div>