config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#homepage"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "admin/login", to: "sessions#create_admin"
  delete "logout", to: "sessions#destroy"
  delete "admin/logout", to: "sessions#destroy_admin"

  resources :users
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "books#index"
    get "login", to: "admin#new"
    get "search", to: "admin#index"
    resources :books
    resources :authors
    resources :publishers
    resources :categories
    resources :requests
    resources :users
  end
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :publisher

  has_many :books, dependent: :nullify
  has_many :follow_authors, dependent: :destroy

  mount_uploader :avatar, PictureUploader

  validates :name, presence: true, length: {maximum: Settings.max_name_email}
  validates :email, presence: true
  validates :phone, presence: true, length: {maximum: Settings.max_phone}
  validates :address, presence: true
  validates :publisher_id, presence: true

  delegate :name, to: :publisher, prefix: true
  delegate :name, to: :category, prefix: true

  scope :list_author_newest, -> {order "created_at desc"}
  scope :list_author_order_name, -> {order "name"}
  scope :search_author_by_name, -> name {where "name like ?", "%#{name}%"}
  scope :search_author_by_publisher, -> name do
    joins(:publisher).select("authors.*").where "publishers.name like ?", "%#{name}%"
  end
  scope :search_author_by_email, -> email {where "email like ?", "%#{name}%"}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :verify_admin
  before_action :load_author, only: [:edit, :destroy, :update]
  before_action :load_publisher, exept: [:show, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:create, :update]

  layout "admin"

  def new
    @author = Author.new
  end

  def index
    respond_to do |format|
      @authors = Author.list_newest_author.paginate page: params[:page],
        per_page: Settings.per_page
      format.html
      format.xlsx
    end
  end

  def create
    @author = Author.new author_params
    if @author.save
      flash[:success] = t "authors.add_author_success"
      redirect_to admin_authors_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update_attributes author_params
      flash[:success] = t "authors.update_success"
      redirect_to admin_authors_url
    else
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = t "authors.delete_success"
    else
      flash[:danger] = t "authors.delete_fail"
    end
    redirect_to admin_authors_url
  end

  private

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:warning] = t "authors.author_not_found"
    redirect_to admin_authors_url
  end

  def load_publisher
    @publishers = Publisher.all
  end

  def author_params
    params.require(:author).permit :name, :email, :phone, :address, :avatar,
      :publisher_id
  end
end

app/views/admin/authors/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("authors.new_author") %></h3>
    </div>
    <div class="modal-body">
      <%= form_for [:admin, @author], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @author.errors[:avatar].any? %>
            <p><span><%= @author.errors[:avatar].first %></span></p>
          <% end %>
          <div class="img-avatar bg">
            <%= image_tag @author.avatar, alt: t("authors.image_alt"),
              id: "thumb" %>
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control",
                readonly: true, placeholder: t("authors.choose_author_avatar") %>
              <%= f.file_field :image, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @author.errors[:name].any? %>
            <p><%= @author.errors[:name].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :name, class: "form-control", id: "name",
              placeholder: t("required") %>
            <%= f.label :name, t("name"), for: "name" %>
          </div>
          <% if @author.errors[:email].any? %>
            <p><span><%= @author.errors[:email].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.email_field :email, class: "form-control", id: "email",
              placeholder: t("required") %>
            <%= f.label :email, t("email"), for: "email" %>
          </div>
          <% if @author.errors[:phone].any? %>
            <p><span><%= @author.errors[:phone].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.phone_field :phone, class: "form-control", id: "phone",
              placeholder: t("required") %>
            <%= f.label :phone, t("phone"), for: "phone" %>
          </div>
          <% if @author.errors[:address].any? %>
            <p><span><%= @author.errors[:address].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :address, class: "form-control", id: "address",
              placeholder: t("required") %>
            <%= f.label :address, t("address"), for: "address" %>
          </div>
          <% if @author.errors[:publisher_id].any? %>
            <p><%= @author.errors[:publisher_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select "publisher_id",
              options_for_select(@publishers.collect{|p| [p.name, p.id]},
                @author.publisher_id.present? ? @author.publisher_id : ""), {},
              class: "form-control custom-select" %>
            <label for="author_publisher_id"><%= t "publisher" %></label>
          </div>
        </div>
        <%= f.submit t("update"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/authors/_index.html.erb
<tr>
  <td><%= col_serial book_counter %></td>
  <td><%= name_limit author.name %></td>
  <td><%= name_limit author.publisher_name %></td>
  <td><%= name_limit author.email %></td>
  <td><%= author.phone %></td>
  <td><%= name_limit author.address %></td>
  <td>
    <%= image_tag author.avatar, alt: t("authors.image_alt") %>
    <div class="edit-delete">
      <%= link_to "", edit_admin_author_path(author), remote: true,
        class: "glyphicon glyphicon-pencil"%>
      <%= link_to "", admin_author_path(author), method: :delete,
        data: {confirm: t("authors.confirm_delete")},
        class: "glyphicon glyphicon-remove" %>
    </div>
  </td>
</tr>

app/views/admin/authors/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("authors.new_author") %></h3>
    </div>
    <div class="modal-body">
      <%= form_for [:admin, @author], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @author.errors[:avatar].any? %>
            <p><span><%= @author.errors[:avatar].first %></span></p>
          <% end %>
          <div class="img-avatar bg">
            <img id="thumb" />
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control",
                readonly: true, placeholder: t("authors.choose_author_avatar") %>
              <%= f.file_field :avatar, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @author.errors[:name].any? %>
            <p><%= @author.errors[:name].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :name, class: "form-control", id: "name",
              placeholder: t("required") %>
            <%= f.label :name, t("name"), for: "name" %>
          </div>
          <% if @author.errors[:email].any? %>
            <p><span><%= @author.errors[:email].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.email_field :email, class: "form-control", id: "email",
              placeholder: t("required") %>
            <%= f.label :email, t("email"), for: "email" %>
          </div>
          <% if @author.errors[:phone].any? %>
            <p><span><%= @author.errors[:phone].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.phone_field :phone, class: "form-control", id: "phone",
              placeholder: t("required") %>
            <%= f.label :phone, t("phone"), for: "phone" %>
          </div>
          <% if @author.errors[:address].any? %>
            <p><span><%= @author.errors[:address].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :address, class: "form-control", id: "address",
              placeholder: t("required") %>
            <%= f.label :address, t("address"), for: "address" %>
          </div>
          <% if @author.errors[:publisher_id].any? %>
            <p><%= @author.errors[:publisher_id].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.select "publisher_id",
              options_for_select(@publishers.collect{|p| [p.name, p.id]}), {},
              class: "form-control custom-select" %>
            <label for="author_publisher_id"><%= t "publisher" %></label>
          </div>
        </div>
        <%= f.submit t("authors.add_new"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/authors/index.html.erb
<div class="manage">
  <div class="btn-head">
    <%= link_to t("authors.new_author"), new_admin_author_path, remote: true,
      class: "btn btn-success btn-new" %>
    <%= link_to t("export"), admin_authors_path(format: :xlsx),
      class: "btn btn-danger btn-export" %>
  </div>
  <div class="list">
    <div>
      <strong><%= t "authors.list_author" %></strong>
      <% flash.each do |key, message| %>
        <span class="alert-<%= key %>"><%= message %></span>
      <% end %>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="stt"><%= t "stt" %></th>
          <th class="title"><%= t "authors.name" %></th>
          <th class="name"><%= t "publishers.name" %></th>
          <th class="name"><%= t "email" %></th>
          <th class="name"><%= t "phone" %></th>
          <th class="name"><%= t "address" %></th>
          <th class="image"><%= t "image" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "index", collection: @authors, as: :author %>
      </tbody>
    </table>
    <%= will_paginate @authors %>
  </div>
</div>