config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#homepage"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  post "admin/login", to: "sessions#create_admin"
  delete "logout", to: "sessions#destroy"
  delete "admin/logout", to: "sessions#destroy_admin"

  resources :users
  resources :account_activations, only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    root "books#index"
    get "login", to: "admin#new"
    get "search", to: "admin#index"
    resources :books
    resources :authors
    resources :publishers
    resources :categories
    resources :requests
    resources :users
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :authors, dependent: :nullify

  mount_uploader :image, PictureUploader

  validates :name, presence: true, length: {maximum: Settings.max_name_email}
  validates :email, presence: true
  validates :phone, presence: true, length: {maximum: Settings.max_phone}
  validates :address, presence: true

  scope :list_publisher_newest, -> {order "created_at desc"}
  scope :list_publisher_order_name, -> {order "name"}
  scope :search_publisher_by_name, -> name {where "name like ?", "%#{name}%"}
  scope :search_publisher_by_email, -> email {where "email like ?", "%#{email}%"}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :verify_admin
  before_action :load_publisher, only: [:edit, :destroy, :update]
  skip_before_filter :verify_authenticity_token, only: [:create, :update]

  layout "admin"

  def new
    @publisher = Publisher.new
  end

  def index
    @publishers = Publisher.list_newest_publisher.paginate page: params[:page],
      per_page: Settings.per_page
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t "publishers.add_publisher_success"
      redirect_to admin_publishers_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update_attributes publisher_params
      flash[:success] = t "publishers.update_success"
      redirect_to admin_publishers_url
    else
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = t "publishers.delete_success"
    else
      flash[:danger] = t "publishers.delete_fail"
    end
    redirect_to admin_publishers_url
  end

  private

  def load_publisher
    @publisher = Publisher.find_by id: params[:id]
    return if @publisher
    flash[:warning] = t "publishers.publisher_not_found"
    redirect_to admin_publishers_url
  end

  def publisher_params
    params.require(:publisher).permit :name, :email, :phone, :address, :image
  end
end

app/views/admin/publishers/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("publishers.new_publisher") %></h3>
    </div>
    <div class="modal-body">
      <%= form_for [:admin, @publisher], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @publisher.errors[:avatar].any? %>
            <p><span><%= @publisher.errors[:avatar].first %></span></p>
          <% end %>
          <div class="img-avatar bg">
            <%= image_tag @publisher.image, alt: t("publishers.image_alt"), id: "thumb" %>
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control", readonly: true,
                placeholder: t("publishers.choose_publisher_image") %>
              <%= f.file_field :image, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @publisher.errors[:name].any? %>
            <p><%= @publisher.errors[:name].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :name, class: "form-control", id: "name",
              placeholder: t("required") %>
            <%= f.label :name, t("name"), for: "name" %>
          </div>
          <% if @publisher.errors[:email].any? %>
            <p><span><%= @publisher.errors[:email].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :email, class: "form-control", id: "email",
              placeholder: t("required") %>
            <%= f.label :email, t("email"), for: "email" %>
          </div>
          <% if @publisher.errors[:phone].any? %>
            <p><span><%= @publisher.errors[:phone].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.phone_field :phone, class: "form-control", id: "phone",
              placeholder: t("required") %>
            <%= f.label :phone, t("phone"), for: "phone" %>
          </div>
          <% if @publisher.errors[:address].any? %>
            <p><span><%= @publisher.errors[:address].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :address, class: "form-control", id: "address",
              placeholder: t("required") %>
            <%= f.label :address, t("address"), for: "address" %>
          </div>
        </div>
        <%= f.submit t("update"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/publishers/_index.html.erb
<tr>
  <td><%= col_serial publisher_counter %></td>
  <td><%= name_limit_publisher publisher.name %></td>
  <td><%= name_limit publisher.email %></td>
  <td><%= publisher.phone %></td>
  <td><%= description_limit publisher.address %></td>
  <td class="image">
    <%= image_tag publisher.image, alt: t("publishers.image_alt") %>
    <div class="edit-delete">
      <%= link_to "", edit_admin_publisher_path(publisher), remote: true,
        class: "glyphicon glyphicon-pencil"%>
      <%= link_to "", admin_publisher_path(publisher), method: :delete,
        data: {confirm: t("publishers.confirm_delete")},
        class: "glyphicon glyphicon-remove" %>
    </div>
  </td>
</tr>

app/views/admin/publishers/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal" aria-hidden="true">
        <small><span class="glyphicon glyphicon-remove"></span></small>
      </button>
      <h3 class="modal-title"><%= t("publishers.new_publisher") %></h3>
    </div>
    <div class="modal-body">
      <%= form_for [:admin, @publisher], remote: true do |f| %>
        <div class="col-md-4 picture">
          <% if @publisher.errors[:image].any? %>
            <p><span><%= @publisher.errors[:image].first %></span></p>
          <% end %>
          <div class="img-avatar bg">
            <img id="thumb" />
          </div>
          <div class="form-group">
            <div>
              <%= text_field_tag "", nil, class: "form-control", readonly: true,
                placeholder: t("publishers.choose_publisher_image") %>
              <%= f.file_field :image, accept: Settings.type_image_accept,
                class: "choose-book-img", onchange: "showMyImage(this)" %>
            </div>
          </div>
        </div>
        <div class="col-md-8 info">
          <% if @publisher.errors[:name].any? %>
            <p><%= @publisher.errors[:name].first %></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :name, class: "form-control", id: "name",
              placeholder: t("required") %>
            <%= f.label :name, t("name"), for: "name" %>
          </div>
          <% if @publisher.errors[:email].any? %>
            <p><span><%= @publisher.errors[:email].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.email_field :email, class: "form-control", id: "email",
              placeholder: t("required") %>
            <%= f.label :email, t("email"), for: "email" %>
          </div>
          <% if @publisher.errors[:phone].any? %>
            <p><span><%= @publisher.errors[:phone].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.phone_field :phone, class: "form-control", id: "phone",
              placeholder: t("required") %>
            <%= f.label :phone, t("phone"), for: "phone" %>
          </div>
          <% if @publisher.errors[:address].any? %>
            <p><span><%= @publisher.errors[:address].first %></span></p>
          <% end %>
          <div class="form-group has-float-label">
            <%= f.text_field :address, class: "form-control", id: "address",
              placeholder: t("required") %>
            <%= f.label :address, t("address"), for: "address" %>
          </div>
        </div>
        <%= f.submit t("publishers.add_new"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/publishers/index.html.erb
<div class="manage">
  <div class="btn-head">
    <%= link_to t("publishers.new_publisher"), new_admin_publisher_path,
      remote: true, class: "btn btn-success btn-new" %>
    <%= link_to t("export"), admin_publishers_path(format: :xlsx),
      class: "btn btn-danger btn-export" %>
  </div>
  <div class="list">
    <div>
      <strong><%= t "publishers.list_publisher" %></strong>
      <% flash.each do |key, message| %>
        <span class="alert-<%= key %>"><%= message %></span>
      <% end %>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="stt"><%= t "stt" %></th>
          <th class="title"><%= t "name" %></th>
          <th class="name"><%= t "email" %></th>
          <th class="name"><%= t "phone" %></th>
          <th class="name"><%= t "address" %></th>
          <th class="image"><%= t "image" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "index", collection: @publishers, as: :publisher %>
      </tbody>
    </table>
    <%= will_paginate @publishers %>
  </div>
</div>